name: CI Build and Test
run-name: "CI Build and Test"
permissions:
  contents: read
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/ci_build.yml
  lint_and_test:
    uses: ./.github/workflows/tox.yml
  azdev_linter:
    needs: [build]
    uses: ./.github/workflows/azdev_linter.yml