name: "Cluster Resource Cleanup"
on:
  # On workflow call (by another workflow) - require all inputs and secrets
  workflow_call:
    inputs:
      cluster_name:
        type: string
        description: "Name of cluster to cleanup"
        required: true
      resource_group:
        type: string
        description: "Resource group to clean up"
        required: true
      keyvault_name:
          type: string
          description: "Keyvault to delete"
          required: true
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
  # On workflow dispatch (manual) - these are not required
  workflow_dispatch:
    inputs:
      resource_group:
        type: string
        description: "Resource group to clean up"
        required: true
        default: ops-cli-int-test-rg
  # Run every night at midnight to cleanup resources
  schedule:
    - cron: '0 0 * * *'

env:
  RESOURCE_GROUP: ${{ inputs.resource_group || 'ops-cli-int-test-rg' }}
  CLUSTER_PREFIX: ${{ inputs.cluster_name || 'az-iot-ops-test-cluster' }}
  KEYVAULT_PREFIX: ${{ inputs.keyvault_name || 'opstestkv' }}

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  arc-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Delete ARC Instances
        run: |
          cluster_type="Microsoft.Kubernetes/connectedClusters"
          for cluster in $(az resource list -g ${{ env.RESOURCE_GROUP }} --resource-type $cluster_type --query "[?starts_with(name, '${{ env.CLUSTER_PREFIX }}')].id" -o tsv); do
            az resource delete --id $cluster --verbose
          done
  keyvault-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Delete Keyvaults
        run: |
          for vault in $(az keyvault list --query "[?starts_with(name, '${{ env.KEYVAULT_PREFIX }}')].name" -o tsv); do
            az keyvault delete -n $vault -g ${{ env.RESOURCE_GROUP }} --no-wait
          done
  resource-cleanup:
    needs: [arc-cleanup]
    runs-on: ubuntu-latest
    steps:
      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Delete Custom Location Resources
        run: |
          for resource in $(az resource list -g ${{ env.RESOURCE_GROUP }} --query "[?starts_with(name, '${{ env.CLUSTER_PREFIX }}')].id" -o tsv); do
            az resource delete --id $resource --verbose
          done
  mq-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Delete MQ Resources
        run: |
          is_mq_child_resource="contains(to_string(type), 'Microsoft.IoTOperationsMQ/mq/')"
          in_cluster_ext_loc="contains(to_string(extendedLocation.name), '${{ env.CLUSTER_PREFIX }}')"

          for mq_resource in $(az resource list -g ${{ env.RESOURCE_GROUP }} --query "[?$in_cluster_ext_loc && $is_mq_child_resource].id" -o tsv); do
            az resource delete --id $mq_resource --verbose
          done
      - name: Delete MQ Instances
        run: |
          mq_type="Microsoft.IoTOperationsMQ/mq"
          in_cluster_ext_loc="contains(to_string(extendedLocation.name), '${{ env.CLUSTER_PREFIX }}')"
          
          # MQ instance cannot be deleted until all child resources have successfully deleted
          sleep 15s

          for mq in $(az resource list -g ${{ env.RESOURCE_GROUP }} --resource-type $mq_type  --query "[?$in_cluster_ext_loc].id" -o tsv); do
            az resource delete --id $mq --verbose
          done