name: Integration tests
on:
  workflow_call:
    outputs:
      aio_deploy_result:
        description: "AIO Deployment result"
        value: ${{ jobs.test.outputs.aio_deploy_results }}
    inputs:
      aio_template:
        description: Template to use for AIO deployment
        type: string
        required: false

jobs:
  test:
    outputs:
      aio_deploy_result: ${{ steps.aio_deploy.outputs.result }}
    permissions:
      contents: 'read'
      id-token: 'write'
    name: Integration test ${{ matrix.py }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.10"
    steps:
      - name: Setup python ${{ matrix.py }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.py }}
      - uses: actions/checkout@v3
      - name: "SETUP CLUSTER"
        run: bash .github/scripts/k3d.sh
      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Build Wheel
        run: |
          pip install wheel==0.30.0
          python -m setup bdist_wheel -d dist
      - name: Install wheel
        run: |
          wheel=$(find ./dist/*.whl)
          echo "wheel=$wheel" >> $GITHUB_ENV
          az extension add --source $wheel -y
      - name: "Create cluster name and RG"
        run: |
            echo "CLUSTER_NAME=az-iot-ops-ext-int-cluster-${{ github.run_id }}-${{ github.run_attempt }}" >> $GITHUB_ENV
            echo "CLUSTER_RG=rk-vnext-rg" >> $GITHUB_ENV
      - name: "ARC_CONNECT"
        run: |
          az extension add --name connectedk8s -y
          az connectedk8s connect -n ${{ env.CLUSTER_NAME }} -g ${{ env.CLUSTER_RG }}
          az connectedk8s enable-features -n ${{ env.CLUSTER_NAME }} -g ${{ env.CLUSTER_RG }} --features custom-locations cluster-connect --custom-locations-oid ${{ secrets.CUSTOM_LOCATIONS_OID }}
      - name: "AIO Deployment"
        id: aio_deploy
        run: >
          result=$(
            az iot ops init
            --cluster ${{ env.CLUSTER_NAME }} -g ${{ env.CLUSTER_RG }}
            --kv-id ${{ secrets.KV_ID }}
            --sp-app-id ${{ secrets.AZURE_CLIENT_ID }}
            --sp-object-id ${{ secrets.AZURE_OBJECT_ID }}
            --sp-secret ${{ secrets.AZURE_CLIENT_SECRET}}
          )
          echo "result=$result" >> $GITHUB_OUTPUT
      - name: Install tox
        run: python -m pip install tox
      - name: Setup test suite
        run: tox r -vv --notest -e "py${{ matrix.py }}-int"
      - name: Show workflow input value
        run:
          echo "Template:"
          echo "${{ inputs.aio_template }}"
      - name: Run test suite
        run: tox r -vv -e "py${{ matrix.py }}-int"
        env:
          AIO_KEYVAULT_NAME: ${{ secrets.AIO_KEYVAULT_NAME }}
          AIO_TENANT_ID: ${{ secrets.AIO_TENANT_ID }}
          AIO_MQTT_EVENTGRID_ENDPOINT: ${{ secrets.AIO_MQTT_EVENTGRID_ENDPOINT }}
      - name: decomm cluster
        if: always()
        run: |
            az connectedk8s delete -n ${{ env.CLUSTER_NAME }} -g ${{ env.CLUSTER_RG }} -y
