on:
    release:
        types: released
    workflow_dispatch:
name: Publish Integration Test Container Image
permissions:
    # required for OpenID federation
    contents: 'read'
    id-token: 'write'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main
      - name: "Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: "Az CLI login"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Login to ACR via OIDC
        run: |
            az acr login --name aziotops
      - name: Determine Version
        run: |
            echo VERSION=$(python -c "from azext_edge import constants; print(constants.VERSION)") >> $GITHUB_ENV
      - name: Build and push container image
        run: |
          az acr build -t aziotops/cli-extension-tests:${{ github.event.release.tag_name || github.ref }} -t ${{ env.VERSION }}  -r aziotops -g ado-int-test-rg .