on:
    release:
        types: released
    workflow_dispatch:
name: publish container to registry
permissions:
    # required for OpenID federation
    contents: 'read'
    id-token: 'write'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main
      - name: "Az CLI login"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Login to ACR via OIDC
        run: |
            az acr login --name aziotops
            az acr build -t azure/azure-iot-ops-cli-extension-tests:${{ github.event.release.tag_name || 'latest' }} -r aziotops .