name: Build and Publish Release
run-name: Build and publish release${{ github.event.inputs.upload_wheel == 'true' &&  ' - Wheel upload' || ''}}${{ github.event.inputs.github_release == 'true' &&  ' - GH release' || ''}}
on:
  # only manual trigger
  workflow_dispatch:
    inputs:
      continue-on-fail:
        description: Continue build even if pre-checks fail
        type: boolean
        required: false
        default: false
      github_release:
        description: Draft a github release
        type: boolean
        required: false
        default: false
      upload_wheel:
        description: Upload wheel to storage
        type: boolean
        required: false
        default: false
jobs:
  # security:
  #   uses: ./.github/workflows/security_checks.yml
  build:
    uses: ./.github/workflows/ci_build.yml
  test:
    uses: ./.github/workflows/tox.yml
  # linter:
  #   needs: [build]
  #   uses: ./.github/workflows/azdev_linter.yml
  # smoke tests are temporarily disabled until a suitable deployment replacement is built
  # smoke_test:
  #   needs: [build]
  #   uses: ./.github/workflows/smoke_test.yml
  approval:
    needs: [build, test]
    # only needed if (release || wheel) AND all steps have succeeded, or build succeeded and break-glass is true
    if: (github.event.inputs.github_release == 'true' || github.event.inputs.upload_wheel == 'true') && (success() || (needs.build.result == 'success' && github.event.inputs.continue-on-fail == 'true'))
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Confirm
        run: |
          echo "Approved"
          if [ "${{ inputs.upload_wheel }}" == "true" ]; then
            echo "Wheel will be uploaded to storage account."
          fi
          if [ "${{ inputs.github_release }}" == "true" ]; then
            echo "Github release will be drafted."
          fi
  # github_release == 'true'
  draft_github_release:
    needs: [approval]
    if: github.event.inputs.github_release == 'true' && (success() || needs.approval.result == 'success')
    uses: ./.github/workflows/stage_release.yml
    secrets: inherit
  # upload_wheel == 'true'
  upload_wheel:
    needs: [approval]
    if: github.event.inputs.upload_wheel == 'true' && (success() || needs.approval.result == 'success')
    uses: ./.github/workflows/upload_wheel.yml
    secrets: inherit
