name: Tox tests
on:
  workflow_call:
    inputs:
      continue-on-error:
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs:
      continue-on-error:
        type: boolean
        required: false
        default: false

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    continue-on-error: ${{ inputs.continue-on-error }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tox
        run: python -m pip install tox
      - name: Run lint
        run: tox -e lint
  test:
    name: Unit test - ${{ matrix.os }}
    continue-on-error: ${{ inputs.continue-on-error }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - windows-2022
          - macos-13
    steps:
      - name: Setup python versions
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.8
            3.9
            3.10
            3.11
            3.12
      - uses: actions/checkout@v4
      - name: Install tox
        run: python -m pip install tox
      - name: Setup test suite
        run: tox r -vv --notest -e "py38,py39,py310,py311,py312" -p
      - name: Run all python unit tests in parallel
        run: tox r -vv --skip-pkg-install -e "py38,py39,py310,py311,py312" -p
  code-coverage:
    name: Calculate code coverage
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run code coverage
        run: |
          python -m pip install tox
          tox -e coverage
          coverage=$(jq .totals.percent_covered coverage.json | cut -c1-4)
          echo "Code coverage: $coverage%" >> $GITHUB_STEP_SUMMARY
      - name: Upload code coverage
        uses: actions/upload-artifact@v4
        with:
          path: ./htmlcov
          name: code_coverage
