name: Tox tests
on:
  workflow_call:
    inputs:
      continue-on-error:
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs:
      continue-on-error:
        description: Continue on error for tests
        type: boolean
        required: false
        default: false

permissions:
  contents: read

jobs:
  tox:
    name: Unit test ${{ matrix.py }} - ${{ matrix.os }}
    continue-on-error: ${{ inputs.continue-on-error }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - windows-2022
          - macos-13
        py:
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
    steps:
      - name: Setup python ${{ matrix.py }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - uses: actions/checkout@v4
      - name: Setup test suite
        run: |
          python -m pip install tox
          if [[ "${{ matrix.py }}" == "3.13" ]]; then
            tox r -e py313 -vv --notest
          else
            tox r -vv --notest
          fi
        shell: bash
      - name: Run test suite
        run: |
          if [[ "${{ matrix.py }}" == "3.13" ]]; then
            tox r -e py313 --skip-pkg-install
          else
            tox r --skip-pkg-install
          fi
        shell: bash
      - name: Upload coverage report
        if: ${{ matrix.os == 'ubuntu-22.04' && matrix.py == '3.12' }}
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          path: ./htmlcov
          name: code_coverage
